package com.mahweb.mahyarnfc.omnishare;
public enum TransferState {
    CREATED, DISCOVERING, NEGOTIATING, AUTHENTICATING, READY, SENDING,
    WAITING_ACK, DELIVERED, FAILED_RETRYABLE, FAILED_FINAL, CANCELLED, EXPIRED
}
